### ISSUE TITLE
No dyno process showing

### ISSUE THREAD

**Issue by phnxXD** [WeebTime/Video-Encoder-Bot#1]
![IMG_20211124_165005](https://user-images.githubusercontent.com/76841477/143229070-b5f0c5c3-e1b5-4c9d-a5f2-8c6871c0c534.jpg)
Please help sir

**Comment by WeebTime** [comment]
Heroku is not supported in this source code.

**Comment by phnxXD** [comment]
Which playfrom i use to deploy

**Comment by WeebTime** [comment]
Google it vro
