### ISSUE TITLE
error (needed help)

### ISSUE THREAD

**Issue by irabro1992** [WeebTime/Video-Encoder-Bot#27]
hello , i changed config.env.template to config.env and i put all of my details in the config.evn.
then i started the bot and it show this error message 

" 2023-07-22 18:57:13,941 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/Video-Encoder-Bot/VideoEncoder/__init__.py", line 33, in <module>
    api_id = int(os.environ.get("API_ID"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

then config.env  file automatically change it back to config.env.template and all settings back to the default.

any idea ? thanks

**Comment by WeebZoneIndia** [comment]
I can't edit the code right now but you can try changing the run.sh file 

remove everything in the file before python3 -m VideoEncoder

**Comment by irabro1992** [comment]
it work now . thanks for your support
